kind: Service
apiVersion: v1
metadata:
  labels:
    name: slackbot
  name: slackbot
spec:
  selector:
    name: slackbot
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
  type: ClusterIP