// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto3.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person3 struct {
	Value                float32              `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Value2               *wrappers.FloatValue `protobuf:"bytes,2,opt,name=value2,proto3" json:"value2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Person3) Reset()         { *m = Person3{} }
func (m *Person3) String() string { return proto.CompactTextString(m) }
func (*Person3) ProtoMessage()    {}
func (*Person3) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fee6d65e34a64b6, []int{0}
}

func (m *Person3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person3.Unmarshal(m, b)
}
func (m *Person3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person3.Marshal(b, m, deterministic)
}
func (m *Person3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person3.Merge(m, src)
}
func (m *Person3) XXX_Size() int {
	return xxx_messageInfo_Person3.Size(m)
}
func (m *Person3) XXX_DiscardUnknown() {
	xxx_messageInfo_Person3.DiscardUnknown(m)
}

var xxx_messageInfo_Person3 proto.InternalMessageInfo

func (m *Person3) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Person3) GetValue2() *wrappers.FloatValue {
	if m != nil {
		return m.Value2
	}
	return nil
}

// p.value=1, p.value2=nil       -> json: {"p":{"value":1}}
// p.value=0, p.value2.value=0   -> json: {"p":{"value2":0}}
// p.value=1, p.value2.value=1   -> json: {"p":{"value":1,"value2":1}}
type Data3 struct {
	P                    *Person3 `protobuf:"bytes,1,opt,name=p,proto3" json:"p,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data3) Reset()         { *m = Data3{} }
func (m *Data3) String() string { return proto.CompactTextString(m) }
func (*Data3) ProtoMessage()    {}
func (*Data3) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fee6d65e34a64b6, []int{1}
}

func (m *Data3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data3.Unmarshal(m, b)
}
func (m *Data3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data3.Marshal(b, m, deterministic)
}
func (m *Data3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data3.Merge(m, src)
}
func (m *Data3) XXX_Size() int {
	return xxx_messageInfo_Data3.Size(m)
}
func (m *Data3) XXX_DiscardUnknown() {
	xxx_messageInfo_Data3.DiscardUnknown(m)
}

var xxx_messageInfo_Data3 proto.InternalMessageInfo

func (m *Data3) GetP() *Person3 {
	if m != nil {
		return m.P
	}
	return nil
}

func init() {
	proto.RegisterType((*Person3)(nil), "example.Person3")
	proto.RegisterType((*Data3)(nil), "example.Data3")
}

func init() { proto.RegisterFile("proto3.proto", fileDescriptor_4fee6d65e34a64b6) }

var fileDescriptor_4fee6d65e34a64b6 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x37, 0xd6, 0x03, 0x53, 0x42, 0xec, 0xa9, 0x15, 0x89, 0xb9, 0x05, 0x39, 0xa9, 0x52, 0x72,
	0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0xe1, 0xa4, 0xd2, 0x34, 0xfd, 0xf2, 0xa2, 0xc4,
	0x82, 0x82, 0xd4, 0xa2, 0x62, 0x88, 0x42, 0xa5, 0x10, 0x2e, 0xf6, 0x80, 0xd4, 0xa2, 0xe2, 0xfc,
	0x3c, 0x63, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xa6, 0x20, 0x08, 0x47, 0xc8, 0x98, 0x8b, 0x0d, 0xcc, 0x30, 0x92, 0x60, 0x52, 0x60, 0xd4, 0xe0,
	0x36, 0x92, 0xd6, 0x83, 0x98, 0xa8, 0x07, 0x33, 0x51, 0xcf, 0x2d, 0x27, 0x3f, 0xb1, 0x24, 0x0c,
	0xa4, 0x26, 0x08, 0xaa, 0x54, 0x49, 0x9d, 0x8b, 0xd5, 0x25, 0xb1, 0x24, 0xd1, 0x58, 0x48, 0x8e,
	0x8b, 0xb1, 0x00, 0x6c, 0x1e, 0xb7, 0x91, 0x80, 0x1e, 0xd4, 0x4d, 0x7a, 0x50, 0x0b, 0x83, 0x18,
	0x0b, 0x92, 0xd8, 0x20, 0xae, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x93, 0x51, 0x91, 0xf8, 0xbe,
	0x00, 0x00, 0x00,
}
