// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(str string, ct int) Event {
	message := NewMessage(str)
	greeter := NewGreeter(message)
	event := NewEvent(greeter, ct)
	return event
}
